baseURL = 'https://www.arts-link.com/'
copyright = "© arts-link.com ⚡ made with ❤️ for a better web"
enableRobotsTXT = true
languageCode = "en-us"
# sectionPagesMenu = "main"
summaryLength = 25
theme = 'ryder-dev'
timeZone = "America/New_York"
title = 'arts-link.com - dev server'

# [services]
#   [services.googleAnalytics]
#     ID = 'G-R4DMQE7FCY'


[params]
  description = "Lightning Fast Portfolios for Artists"
  isAlpha = true
   
  headerGradientClasses = "bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500" 

[[params.alphaAlert]]
  alertType = "warning"
  alertTitle = "Alpha version"
  alertMessage = "The redesign of arts-link.com is in progress and happening live in front of your eyes! Please consider this a prototype with no design at this point."
  alertIconClass = "fa-solid fa-camera-retro"
[[params.author]]
  name = "Ben Strawbridge"
[[params.social]]
  faClasses = "fa-solid fa-envelope"
  title = "Email me"
  url   = "mailto:hello@arts-link.com?subject=web"
  target= "_blank"
  weight = 30 
[[params.social]]
  faClasses = "fa-brands fa-github"
  title = "GitHub"
  url   = "https://www.github.com/arts-link"
  target= "_blank"
  weight = 20

# [menus]
# [[menus.main]]
#   name = 'For Galleries'
#   url = '/for-galleries/'
#   weight = 10
# [[menus.main]]
#   name = 'For Artists'
#   url = '/for-artists/'
#   weight = 20
# [[menus.main]]
#   name = 'Portfolio Features'
#   url = '/features/'
#   weight = 30
# [[menus.main]]
#   name = 'About'
#   url = '/about/'
#   weight = 50
# [[menus.main]]
#   name = 'Services'
#   url = '/services/'
#   weight = 30

[build]
  writeStats = true
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
