baseURL = 'https://www.arts-link.com/'
title = 'arts-link.com - dev server'
theme = 'benstraw'
languageCode = "en-us"
copyright = "© arts-link.com ⚡"

enableRobotsTXT = true
timeZone = "America/New_York"

[params]
  title = "arts-link.com"
  description = "Lightning Fast Portfolios for Artists"


[[params.author]]
  name = "Ben Strawbridge"
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
