baseURL = 'https://www.arts-link.com/'
copyright = "© arts-link.com ⚡"
enableRobotsTXT = true
languageCode = "en-us"
# sectionPagesMenu = "main"
summaryLength = 25
theme = 'ryder-dev'
# theme = 'ryder'
timeZone = "America/Los_Angeles"
title = 'arts-link.com dev'
enableEmoji = true
enableGitInfo = true
[params]
  description = "⚡ Lightning-Fast Portfolios for Artists ⚡"
  isAlpha = true
  headerGradientClasses = "bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500" 
  showDarkToggle = true
  logo_tagline = "⚡ LIGHTNING-FAST PORTFOLIOS ⚡"
  repository = "https://github.com/arts-link/arts-link.com"
  showHomeTitle = true
  # homePageFeatureHeader = "Featured Sites"
  # og_image_default = "/images/sunset-mission-bay.jpg"
  showHomeFeed = false 
  showSummaryMeta = false
# [[params.alphaAlert]]
#   alertType = "warning"
#   alertTitle = "Alpha version"
#   alertMessage = "The redesign of arts-link.com is in progress and happening live in front of your eyes! Please consider this a prototype with little design at this point."
#   alertIconClass = "fa-solid fa-camera-retro"
[params.author]
  name = "Ben Strawbridge"
  email = "hello@arts-link.com"
[params.twClasses]
  # headerBackgroundFrameOuter = "bg-gradient-to-r to-zinc-400 from-zinc-900 dark:from-violet-950 dark:to-rose-950 border-b border-fuchsia-600 text-zinc-200 dark:text-neutral-100"
  headerBackgroundFrameOuter = "bg-zinc-200 dark:bg-rose-950 border-b border-fuchsia-600 text-zinc-800 dark:text-neutral-100"
  # headerBackgroundFrameInner = ""
  headerBackgroundFrameInner = "bg-paint-drip h-[150px] sm:h-[150px] bg-auto bg-repeat-x"


[build]
  writeStats = true
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
