baseURL = 'https://www.arts-link.com/'
title = 'arts-link.com - dev server'
theme = 'benstraw'
languageCode = "en-us"
copyright = "© arts-link.com ⚡"

enableRobotsTXT = true
timeZone = "America/New_York"

[params]
  description = "Lightning Fast Portfolios for Artists"
  isAlpha = true
[[params.author]]
  name = "Ben Strawbridge"

[menus]
[[menus.main]]
  name = 'For Galleries'
  url = '/galleries/'
  weight = 10
[[menus.main]]
  name = 'For Artists'
  url = '/artists/'
  weight = 20
[[menus.main]]
  name = 'Portfolio Features'
  url = '/features/'
  weight = 30
[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 50
# [[menus.main]]
#   name = 'Services'
#   url = '/services/'
#   weight = 30

[build]
  writeStats = true
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
