baseURL = 'https://www.arts-link.com/'
copyright = "© arts-link.com ⚡"
enableRobotsTXT = true
languageCode = "en-us"
# sectionPagesMenu = "main"
summaryLength = 25
theme = 'ryder-dev'
# theme = 'ryder'
timeZone = "America/Los_Angeles"
title = 'arts-link.com dev'
enableEmoji = true
enableGitInfo = false 
  

[build]
  writeStats = true
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
