baseURL = 'https://www.arts-link.com/'
copyright = "© arts-link.com ⚡"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]
languageCode = "en-us"
# sectionPagesMenu = "main"
summaryLength = 25
timeZone = "America/Los_Angeles"
title = 'arts-link.com dev'
enableEmoji = true
enableGitInfo = false 
  

[build]
  writeStats = true

[outputFormats.llmstxt]
  mediaType = "text/plain"
  baseName = "llms"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "llmstxt"]
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
