baseURL = 'https://www.arts-link.com/'
copyright = "© arts-link.com ⚡"
enableRobotsTXT = true
languageCode = "en-us"
summaryLength = 25
theme = 'benstraw'
timeZone = "America/New_York"
title = 'arts-link.com - dev server'

[params]
  description = "Lightning Fast Portfolios for Artists"
  isAlpha = true
[[params.author]]
  name = "Ben Strawbridge"
[[params.social]]
  faClasses = "fa-solid fa-envelope"
  title = "Email me"
  url   = "mailto:ben@benstrawbridge.com?subject=web"
  target= "_blank"
  weight = 30 
[[params.social]]
  faClasses = "fa-brands fa-github"
  title = "GitHub"
  url   = "https://www.github.com/arts-link"
  target= "_blank"
  weight = 20

[menus]
[[menus.main]]
  name = 'For Galleries'
  url = '/galleries/'
  weight = 10
[[menus.main]]
  name = 'For Artists'
  url = '/artists/'
  weight = 20
[[menus.main]]
  name = 'Portfolio Features'
  url = '/features/'
  weight = 30
[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 50
# [[menus.main]]
#   name = 'Services'
#   url = '/services/'
#   weight = 30

[build]
  writeStats = true
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
