description = "⚡ Lightning-Fast Portfolios for Artists ⚡"
isAlpha = true
headerGradientClasses = "bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500" 
showDarkToggle = true
logo_tagline = "⚡ LIGHTNING-FAST PORTFOLIOS ⚡"
repository = "https://github.com/arts-link/arts-link.com"
hideAttribution = true
showHomeTitle = true
# card settings
showCardLinkOverlay = false
showReadOn = true
showSummaryMeta = false
showHomeFeed = false 
[author]
  name = "Ben Strawbridge"
  email = "hello@arts-link.com"
[twClasses]
  # headerBackgroundFrameOuter = "bg-gradient-to-r to-zinc-400 from-zinc-900 dark:from-violet-950 dark:to-rose-950 border-b border-fuchsia-600 text-zinc-200 dark:text-neutral-100"
  headerBackgroundFrameOuter = "bg-zinc-200 dark:bg-rose-950 border-b border-fuchsia-600 text-zinc-800 dark:text-neutral-100"
  # headerBackgroundFrameInner = ""
  headerBackgroundFrameInner = "bg-paint-drip h-[150px] sm:h-[150px] bg-auto bg-repeat-x"
