description = "Bespoke websites for artists and bands. Fast, personal, and yours to keep."
formspree_id = ""  # Add your Formspree form ID here

[author]
  name = "Ben Strawbridge"
  email = "hello@arts-link.com"
