title = 'ARTS-LINK'
theme = 'ryder'


[params]
  env = "production"
  plausible_domain = "arts-link.com"
  plausible_advanced = true

# [services]
#   [services.googleAnalytics]
#     ID = 'G-R4DMQE7FCY'
