title = 'ARTS-LINK'

[params]
  env = "production"
  posthog_key = "phc_6ETRdmu3rRItmhyAtxqdN8umjqSAWMRKYVvlu35GMJ7"
  posthog_host = "https://g.arts-link.com"

# [services]
#   [services.googleAnalytics]
#     ID = 'G-R4DMQE7FCY'
